-- ========================================
-- Supabase (PostgreSQL) schema for us_job_hunt
-- 用途：在 Supabase SQL Editor 中一次性创建后端需要的表结构
-- 说明：这是“结构迁移”脚本，不包含 MySQL 数据搬迁
-- ========================================

-- 1) 用户表
CREATE TABLE IF NOT EXISTS local_users (
    user_id BIGINT PRIMARY KEY,
    id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    phone VARCHAR(20),
    target_companies TEXT,
    experience_years INTEGER,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_token VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_local_users_email ON local_users(email);
CREATE INDEX IF NOT EXISTS idx_local_users_created_at ON local_users(created_at);

-- 2) 订单表
CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT PRIMARY KEY,
    id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id BIGINT NOT NULL,
    plan_name VARCHAR(50) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(50),
    transaction_id VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    bilibili_account VARCHAR(100),
    phone VARCHAR(20),
    info_submitted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_orders_user_id
        FOREIGN KEY (user_id) REFERENCES local_users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_orders_status
        CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED'))
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_transaction_id ON orders(transaction_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_user_id_status ON orders(user_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_expires_at ON orders(expires_at);

-- 3) 会员表
CREATE TABLE IF NOT EXISTS user_memberships (
    user_id BIGINT PRIMARY KEY,
    membership_expiry_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memberships_user_id
        FOREIGN KEY (user_id) REFERENCES local_users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_memberships_expiry_time ON user_memberships(membership_expiry_time);

-- ========================================
-- 可选：快速检查
-- ========================================
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'local_users';
